//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edubin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Batch_Details()
        {
            this.Course_Details = new HashSet<Course_Details>();
        }
    
        public string Batch_Code { get; set; }
        public System.DateTime Batch_Start { get; set; }
        public System.DateTime Batch_end { get; set; }
        public System.TimeSpan Timing { get; set; }
        public int Faculty { get; set; }
    
        public virtual Faculty_Details Faculty_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Details> Course_Details { get; set; }
    }
}
