//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edubin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faculty_Details()
        {
            this.Batch_Details = new HashSet<Batch_Details>();
        }
    
        public int F_id { get; set; }
        public string F_name { get; set; }
        public string Email { get; set; }
        public long Contact { get; set; }
        public int F_User { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch_Details> Batch_Details { get; set; }
        public virtual User User { get; set; }
    }
}
