//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edubin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EdubinEntities : DbContext
    {
        public EdubinEntities()
            : base("name=EdubinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<RolesMapper> RolesMappers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Batch_Details> Batch_Details { get; set; }
        public virtual DbSet<Course_Details> Course_Details { get; set; }
        public virtual DbSet<Course_Fee> Course_Fee { get; set; }
        public virtual DbSet<Exam_Details> Exam_Details { get; set; }
        public virtual DbSet<Exam_Result> Exam_Result { get; set; }
        public virtual DbSet<Faculty_Details> Faculty_Details { get; set; }
        public virtual DbSet<Student_Details> Student_Details { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
