//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edubin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_Details()
        {
            this.Exam_Details = new HashSet<Exam_Details>();
            this.Exam_Result = new HashSet<Exam_Result>();
        }
    
        public int Std_Id { get; set; }
        public string C_Name { get; set; }
        public System.DateTime D_O_B { get; set; }
        public string Email { get; set; }
        public long Contact { get; set; }
        public System.DateTime D_O_A { get; set; }
        public int User_ { get; set; }
        public string Batch { get; set; }
        public string Course { get; set; }
    
        public virtual Course_Details Course_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_Details> Exam_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_Result> Exam_Result { get; set; }
        public virtual User User { get; set; }
    }
}
